### ISSUE TITLE
ModuleNotFoundError: No module named 'coleridge_datasets'

### ISSUE THREAD

**Issue by tphankr** [gallegi/T4E_MICCAI_BrainTumor#1]
Please help me, how to fix this error. This error is the line 15 of general.py file. 
I also try to type " pip intall coleridge_datasets", but is not sucessful. Thank you @gallegi.
![image](https://user-images.githubusercontent.com/37217354/138608016-345e2c07-f403-49de-8236-28afc3cdd83c.png)
Thank you.

**Comment by gallegi** [comment]
Thanks for your feedback, I will fix the issue

**Comment by gallegi** [comment]
It is my redundant import from the last project. Sorry for that. I have
already pushed the fixed version to Github, please pull back and rerun. If
there is any other issue, please let me know. Thanks.

**Comment by gallegi** [comment]
Issue done, I guess I can close it now
